// <auto-generated />
using AD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AD.Migrations
{
    [DbContext(typeof(ADContext))]
    [Migration("20181024014744_Employee")]
    partial class Employee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AD.Employee", b =>
                {
                    b.Property<int>("Employee_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin_Flag");

                    b.Property<string>("Bureau")
                        .HasMaxLength(50);

                    b.Property<string>("Cell_Phone")
                        .HasMaxLength(25);

                    b.Property<string>("Department")
                        .HasMaxLength(50);

                    b.Property<string>("Department_Code")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Employee_Number")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Middle_Name")
                        .HasMaxLength(50);

                    b.Property<string>("Payroll_Title")
                        .HasMaxLength(50);

                    b.Property<string>("Unit")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .HasMaxLength(50);

                    b.Property<string>("Work_City")
                        .HasMaxLength(100);

                    b.Property<string>("Work_Location")
                        .HasMaxLength(100);

                    b.Property<string>("Work_Phone")
                        .HasMaxLength(10);

                    b.Property<string>("Work_State")
                        .HasMaxLength(100);

                    b.Property<string>("Work_Zip")
                        .HasMaxLength(25);

                    b.Property<string>("Work_address")
                        .HasMaxLength(50);

                    b.HasKey("Employee_ID");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
